// Economics of Global Business, week 1: course intro and national accounts
// (intro slides + "Macroeconomic Data: National Accounts" slides; Mankiw ch. 2).
window.VOCAB_SETS = window.VOCAB_SETS || [];
window.VOCAB_SETS.push({
  id: "egb-week1",
  course: "Economics of Global Business",
  week: 1,
  title: "Intro and National Accounts",
  materials: ["Week_1_Intro_Economics_of_Global_Business.pdf", "Macroeconomic_Data_National_Accounts.pdf"],
  cards: [
    // ---------- big picture ----------
    { term: "Macroeconomics",
      definition: "The study of how the collection of people and firms in a region interact through markets to determine its overall economic activity: growth, business cycles, inflation, unemployment." },
    { term: "Long-run growth", alt: ["Long run growth", "Economic growth"],
      definition: "The sustained rise in a country's output over decades, about 3% per year for the US, driven by population growth, labor force participation, and rising labor productivity." },
    { term: "Business cycle", alt: ["Business cycles"],
      definition: "The short-run declines and expansions of output around its long-run trend." },
    { term: "Average labor productivity", alt: ["Labor productivity", "Output per worker"],
      definition: "Output divided by the number of employed workers; a main source of growth in output per person." },
    { term: "Demand-side shock", alt: ["Demand shock"],
      definition: "A sudden change in overall spending in the economy, such as a central bank unexpectedly signalling higher interest rates." },
    { term: "Supply-side shock", alt: ["Supply shock"],
      definition: "A sudden change in the cost or availability of what the economy produces with, such as an oil price surge after an attack on shipping." },
    { term: "Hawkish",
      definition: "Describes a central bank stance that leans toward higher interest rates to fight inflation, even at the cost of slower growth; the opposite is dovish." },
    // ---------- GDP ----------
    { term: "Gross domestic product", alt: ["GDP"],
      definition: "The market value of all final goods and services newly produced within a country's borders during a fixed period, before subtracting depreciation." },
    { term: "Final goods", alt: ["Final good", "Final goods and services"],
      definition: "Goods and services bought by their end user rather than used up in making something else; only these are counted in GDP to avoid double counting." },
    { term: "Intermediate goods", alt: ["Intermediate good", "Intermediates"],
      definition: "Goods used up as inputs in producing other goods, like lithium in a battery or a landing system in an airplane; their value is already inside the final good's price." },
    { term: "Double counting",
      definition: "The error of adding the value of an input and then again the value of the product that contains it; avoided by counting only final goods or only value added." },
    { term: "Value added",
      definition: "A producer's sales minus the cost of the material inputs it bought; summed across all producers it equals GDP." },
    { term: "Value-added approach", alt: ["Value added approach", "Production approach"],
      definition: "Computing GDP by summing each producer's sales minus material input costs across the whole economy." },
    { term: "Income approach",
      definition: "Computing GDP by summing all payments to labor and capital (wages, profits, interest, rent); it matches GDP apart from items like depreciation and capital gains." },
    { term: "Expenditure approach",
      definition: "Computing GDP by summing purchases of final goods and services: consumption plus investment plus government purchases plus net exports." },
    { term: "Depreciation", alt: ["Capital consumption"],
      definition: "The wearing out of capital such as machines and buildings; \"gross\" in GDP means it has not been subtracted." },
    { term: "Home production",
      definition: "Goods and services people make for themselves without a market transaction, like cooking or childcare; left out of GDP because there is no market price." },
    { term: "Underground economy", alt: ["Informal economy", "Shadow economy"],
      definition: "Economic activity hidden from official records, whether illegal or simply unreported; missing from GDP." },
    // ---------- expenditure identity ----------
    { term: "GDP expenditure identity", alt: ["Expenditure identity", "GDP identity", "Y = C + I + G + NX"],
      definition: "The accounting equation GDP = C + I + G + NX: output equals consumption plus investment plus government purchases plus net exports." },
    { term: "Consumption", alt: ["Consumer spending", "C"],
      definition: "Final sales of new goods and services to households: durables, nondurables, and services." },
    { term: "Durable goods", alt: ["Durables"],
      definition: "Long-lasting consumer goods such as cars and appliances, one of the three parts of household spending alongside nondurables and services." },
    { term: "Investment", alt: ["Gross investment", "I"],
      definition: "Final sales of new capital goods to firms (plant and equipment), plus the change in inventories and spending on housing; not the purchase of stocks or bonds." },
    { term: "Inventory investment",
      definition: "The change in unsold or in-process goods held by firms; treated in the national accounts as if firms bought those goods from themselves." },
    { term: "Government purchases", alt: ["Government spending", "G"],
      definition: "Government buying of new goods and services, from aircraft carriers to teachers' salaries; excludes transfer payments." },
    { term: "Transfer payments", alt: ["Transfers", "Transfer payment"],
      definition: "Government payments made without receiving a good or service in return, such as food stamps, unemployment insurance, and Social Security; not counted in GDP." },
    { term: "Net exports", alt: ["NX", "Trade balance"],
      definition: "Exports minus imports: the value of goods and services sold to other countries less the value bought from them." },
    { term: "National Income and Product Accounts", alt: ["NIPA", "National income accounts"],
      definition: "The official US accounts of GDP and its components, published by the BEA; each quarter's figure is released in three successive estimates, 1, 2, and 3 months after the quarter ends." },
    { term: "Bureau of Economic Analysis", alt: ["BEA"],
      definition: "The US Commerce Department agency that produces the GDP and national income statistics." },
    { term: "Bureau of Labor Statistics", alt: ["BLS"],
      definition: "The US agency that produces the monthly employment report, the unemployment rate, and the consumer price index." },
    { term: "FRED", alt: ["Federal Reserve Economic Database", "Federal Reserve Economic Data"],
      definition: "The St. Louis Fed's free online database of economic time series, with graphing tools and Excel downloads; you look up series by code." },
    // ---------- prices vs quantities ----------
    { term: "Nominal GDP", alt: ["GDP at current prices", "Current-dollar GDP"],
      definition: "Output valued at the prices of the same year it was produced: price times quantity, so it rises with both inflation and real growth." },
    { term: "Real GDP", alt: ["GDP at constant prices", "GDP at base-year prices"],
      definition: "Output valued at the prices of a fixed base year, so changes reflect quantities rather than prices." },
    { term: "Base year",
      definition: "The reference year whose prices are used to value output and whose price index is set to 1 (or 100)." },
    { term: "Price index",
      definition: "The price level in a given year divided by the price level in the base year; dividing nominal GDP by it gives real GDP." },
    { term: "Inflation",
      definition: "The percentage change in a price index between two consecutive periods." },
    { term: "GDP deflator", alt: ["GDP price deflator", "Price deflator", "Implicit price deflator"],
      definition: "Nominal GDP divided by real GDP; a price index covering everything produced domestically, whose basket changes with what is actually produced." },
    { term: "Consumer price index", alt: ["CPI"],
      definition: "A price index that values a fixed base-year basket of consumer goods and services, including imports, at current prices." },
    { term: "Substitution bias",
      definition: "The distortion in fixed-basket measures that ignores buyers shifting toward goods whose relative prices fall; it makes fixed-weight real GDP growth depend on how far back the base year is." },
    { term: "Chain-weighted real GDP", alt: ["Chain-weighted GDP", "Chained dollars", "Chain weighting"],
      definition: "Real GDP computed as a geometric average using two adjacent years' prices, so the base year updates continually; its components no longer add up exactly to the total." },
    { term: "Purchasing power parity", alt: ["PPP", "Purchasing power adjustment"],
      definition: "Valuing different countries' output at a common set of prices so that comparisons reflect quantities, not differences in the cost of living." },
    { term: "GDP per capita", alt: ["Output per capita", "Per capita GDP"],
      definition: "Output divided by population; the scale used to compare how rich countries are rather than how big they are." },
    // ---------- labor market ----------
    { term: "Adult population", alt: ["Working-age population", "Civilian noninstitutional population"],
      definition: "Everyone old enough to work who is not in the military or an institution; the base for the labor force participation rate." },
    { term: "Labor force", alt: ["Labour force"],
      definition: "The employed plus the unemployed: everyone working at a paid job or available for work and looking." },
    { term: "Employed",
      definition: "Working at a paid job during the survey week, full time or part time." },
    { term: "Unemployed",
      definition: "Not working but available for work and actively looking for a job." },
    { term: "Not in the labor force", alt: ["Out of the labor force", "Not in labor force"],
      definition: "Neither working nor looking for work: students, retirees, homemakers, discouraged workers." },
    { term: "Unemployment rate",
      definition: "The unemployed as a percentage of the labor force, e.g. 7.0 million out of 169.8 million is 4.1%." },
    { term: "Labor force participation rate", alt: ["Participation rate", "LFPR", "LFP rate"],
      definition: "The labor force as a percentage of the adult population, e.g. 169.8 million out of 275.4 million is 61.6%." },
    { term: "Employment-to-population ratio", alt: ["Employment to population ratio", "E/P ratio", "E-P ratio", "Employment-population ratio"],
      definition: "The employed as a percentage of the adult population; it fell more in the pandemic than in any earlier recession and recovered quickly." },
    { term: "Nonfarm payrolls", alt: ["Nonfarm payroll employment", "Payroll employment"],
      definition: "The headline monthly count of jobs at US employers excluding farms, reported by the BLS alongside the unemployment rate." },
    { term: "Mankiw", kind: "person", alt: ["N. Gregory Mankiw", "Gregory Mankiw"],
      definition: "Author of Macroeconomics, the course textbook; chapter 2 covers GDP, price indexes, and the labor market data." }
  ]
});
