// Week 1: An Introduction to Ethics (based on Kwame Anthony Appiah,
// "Thinking It Through" ch. 5 and "Experiments in Ethics" ch. 2) and
// Appiah, "Cross-cultural Conversation" (from Cosmopolitanism, 2006).
//
// Each card: { term, definition, alt?, kind? }
//   term       – what you must type
//   definition – what is shown as the prompt
//   alt        – other typed answers accepted as correct (optional)
//   kind       – "person" for philosophers and works; hidden unless the
//                "Include philosophers & works" box is ticked (optional)
window.VOCAB_SETS = window.VOCAB_SETS || [];
window.VOCAB_SETS.push({
  id: "ethics-week1",
  course: "Ethics",
  week: 1,
  title: "Introduction and Cross-Cultural Conversation",
  materials: ["Week_1_An_Introduction_to_Ethics.pdf", "Week_1_Appiah_CrossCultural_Conversation__Global_Ethics.pdf"],
  cards: [
    // ---------- Part I: Meta-ethics ----------
    { src: [0], term: "Euthanasia",
      definition: "Killing a seriously ill person in great pain who asks to be killed; from a Greek expression meaning \"a good death.\"" },
    { src: [0], term: "First-order moral questions", alt: ["First-order questions", "First order moral questions", "First-order"],
      definition: "Questions about what is right and wrong, good and bad; questions about which moral beliefs we should accept." },
    { src: [0], term: "Meta-ethics", alt: ["Metaethics", "Meta-ethical questions"],
      definition: "Second-order questions about the nature, structure, and status of our first-order moral views." },
    { src: [0], term: "Empiricism",
      definition: "The view that questions are to be settled by observation and experiment; does not seem a plausible view about morality." },
    { src: [0], term: "A priori",
      definition: "Truths that can be known by reason alone, prior to (before) any particular experience; e.g. \"Green things are colored.\"" },
    { src: [0], term: "A posteriori",
      definition: "Truths that require more than reason to discover; they can only be known after experience." },
    { src: [0], term: "Epistemology",
      definition: "The study of the nature of knowledge and the justification of belief." },
    { src: [0], term: "Moral rationalism",
      definition: "The view that moral questions are to be discovered by reason." },
    { src: [0], term: "Factual questions", alt: ["Factual question", "Matters of fact"],
      definition: "Questions that observation, experiment, or proof alone can help us settle; there is a matter of fact about whether they are true, and logic and experience are ways of finding out." },
    { src: [0], term: "Evaluative claim", alt: ["Evaluative claims", "Evaluative question", "Matters of value", "Matter of value"],
      definition: "A claim about value rather than fact; accepting one commits you to certain courses of action (you cannot reasonably accept that an act is wrong and then go ahead and do it)." },
    { src: [0], term: "All things considered ought", alt: ["All things considered", "\"All things considered\" ought"],
      definition: "The kind of \"ought\" you assert once every relevant reason for and against acting has been weighed; it commits you to a course of action and is central to moral thinking." },
    { src: [0], kind: "person", term: "David Hume", alt: ["Hume"],
      definition: "Eighteenth-century Scottish philosopher (1711-1776) who was one of the first to frame the difference between factual and evaluative questions as the difference between what is so and what ought to be so." },
    { src: [0], term: "Fact-value distinction", alt: ["Fact/value distinction", "Is-ought distinction", "Is/ought distinction", "Is-ought gap"],
      definition: "The split between what is so and what ought to be so, central to all meta-ethics since Hume; summarized in the slogan \"you can't derive an 'ought' from an 'is.'\"" },
    { src: [0], term: "Moral content question", alt: ["The moral content question"],
      definition: "The first of the two great questions of meta-ethics: \"What do moral judgments mean?\"" },
    { src: [0], term: "Moral epistemology",
      definition: "The part of meta-ethics that answers the second great question, \"What justifies moral judgments?\"; it must show how moral beliefs are justified differently from factual ones." },
    { src: [0], term: "Moral realism", alt: ["Realism"],
      definition: "The view that, just as ordinary facts \"out there\" determine whether factual claims are true, there are moral facts that determine the truth-values of moral claims." },
    { src: [0], term: "Action-guiding", alt: ["Action guiding"],
      definition: "Said of beliefs that commit us to action whatever our preferences or desires, as moral beliefs do; factual beliefs guide action only when combined with a desire." },
    { src: [0], term: "Categorical imperative", alt: ["Categorical imperatives"],
      definition: "Kant's name for an \"ought\" that a speaker would still assert whatever you said your wants and desires were." },
    { src: [0], term: "Hypothetical imperative", alt: ["Hypothetical imperatives"],
      definition: "An \"ought\" that depends on a hypothesis about what you want, e.g. \"If you want to get there quickly, you ought to take a taxi.\"" },
    { src: [0], kind: "person", term: "Immanuel Kant", alt: ["Kant"],
      definition: "German philosopher of the Enlightenment (1724-1804) who distinguished categorical from hypothetical imperatives and proposed the universalizability principle." },
    { src: [0], kind: "person", term: "Elizabeth Anscombe", alt: ["Anscombe", "G. E. M. Anscombe"],
      definition: "British philosopher (1919-2001) who said \"The primitive sign of wanting is trying to get,\" cited to show that desires, unlike factual beliefs, lead directly to action." },
    { src: [0], term: "Emotivism",
      definition: "The view that moral sentences express not beliefs but feelings, preferences, or desires (action-guiding states of mind)." },
    { src: [0], term: "Pro-attitudes", alt: ["Pro-attitude", "Pro attitudes", "Pro attitude"],
      definition: "Action-guiding mental states that dispose you towards doing something." },
    { src: [0], term: "Con-attitudes", alt: ["Con-attitude", "Con attitudes", "Con attitude"],
      definition: "Action-guiding mental states that dispose you against some action." },
    { src: [0], term: "Attitudes", alt: ["Attitude"],
      definition: "Umbrella term for the mental states that dispose you for or against an action (the \"pro\" and \"con\" kinds taken together)." },
    { src: [0], term: "Cognitivism",
      definition: "The view in moral epistemology that we can have moral knowledge; tends to go with moral realism." },
    { src: [0], term: "Non-cognitivism", alt: ["Noncognitivism", "Non cognitivism"],
      definition: "The view in moral epistemology that we cannot have moral knowledge, because moral sentences express attitudes, which cannot be true or false; tends to go with emotivism." },
    { src: [0], term: "Intuitionism",
      definition: "G. E. Moore's form of cognitivism: we have a faculty that allows us to perceive moral qualities, just as the faculty of vision allows us to see colors." },
    { src: [0], term: "Moral intuition",
      definition: "The faculty that, according to the intuitionist, lets us perceive goodness directly, the way vision lets us perceive yellowness." },
    { src: [0], kind: "person", term: "G. E. Moore", alt: ["Moore", "GE Moore", "G.E. Moore", "George Edward Moore"],
      definition: "English philosopher (1873-1958), author of Principia Ethica, who combined moral realism with intuitionism and took goodness (not rightness or duty) as the basic moral concept." },
    { src: [0], kind: "person", term: "Principia Ethica",
      definition: "Moore's book in which an action is one's duty \"if it will cause more good to exist in the universe than any other possible kind of alternative.\"" },
    { src: [0], term: "Non-natural property", alt: ["Non-natural", "Nonnatural property"],
      definition: "Moore's description of goodness: a property that, unlike yellowness, cannot be studied by natural scientists or defined in terms of any other notions." },
    { src: [0], term: "Natural property", alt: ["Natural properties"],
      definition: "Moore's term for properties like yellowness: the sorts of properties that could be studied by natural scientists." },
    { src: [0], term: "Naturalistic fallacy",
      definition: "Moore's name for any attempt to identify a natural property with a non-natural one; now often used for any attempt to derive an \"ought\" from an \"is.\"" },
    { src: [0], term: "Hedonism", alt: ["Hedonists", "Hedonist"],
      definition: "The view that once we know something gives people pleasure we can infer that it is good; the first utilitarians held it, since they sought to maximize happiness." },
    { src: [0], kind: "person", term: "Alasdair MacIntyre", alt: ["MacIntyre"],
      definition: "British philosopher (1929-) who objected that Moore's view leaves it unexplained why something's being good should ever give us a reason for action; the analogy with yellow is a difficulty for it." },
    { src: [0], term: "Moral relativism", alt: ["Relativism"],
      definition: "The view that what is good depends on who you are (or in what culture or when you live)." },
    { src: [0], term: "Basic desire", alt: ["Basic desires"],
      definition: "A desire that is not dependent on a belief about means to some end; something we want \"for its own sake\" (e.g. wanting a friend to have a good afternoon)." },
    { src: [0], term: "Universalizability principle", alt: ["Universalizability", "Kant's universalizability principle", "Principle of universalizability"],
      definition: "Kant's single categorical imperative: you ought to act only on maxims that you can at the same time will should become universal laws of nature." },
    { src: [0], term: "Maxim", alt: ["Maxims"],
      definition: "Your general reason for acting in a particular way; the principle you must identify and then imagine becoming a law of nature when applying Kant's test." },
    { src: [0], kind: "person", term: "Groundwork of the Metaphysic of Morals", alt: ["Groundwork", "Groundwork of the Metaphysics of Morals"],
      definition: "Kant's work arguing that the universalizability principle is the only categorical imperative, from which all the principles of morality derive." },
    { src: [0], term: "Golden Rule", alt: ["The Golden Rule"],
      definition: "\"Do unto others as you would have them do unto you\": you shouldn't treat anybody in a way you would not like to be treated, whatever their race, gender, or age." },
    { src: [0], kind: "person", term: "R. M. Hare", alt: ["Hare", "RM Hare", "R.M. Hare", "Richard Hare"],
      definition: "British philosopher (1919-2002), a prescriptivist and utilitarian, who added to Kant's formal demands the conditions that we treat everybody equally and consider consequences for sentient beings." },
    { src: [0], term: "Sentient beings", alt: ["Sentient being"],
      definition: "Creatures capable, like us, of having experiences; Hare says we should consider the effects of possible actions on them." },
    { src: [0], term: "Fanatic", alt: ["Fanatics"],
      definition: "Hare's name for someone willing to universalize maxims that allow them to do things to other people that they would not like done to themselves; there is something wrong with their imagination." },
    { src: [0], term: "Prescriptivism",
      definition: "Hare's account of moral content: the meaning of moral terms is never equivalent to descriptive terms; moral sentences prescribe rather than describe, expressing attitudes and not just beliefs." },
    { src: [0], term: "Supervenience", alt: ["Supervenient", "Supervene"],
      definition: "The relation whereby two actions or situations identical in their non-moral features must, as a matter of necessity, share their moral ones (compare: chemical properties on physical ones)." },
    // ---------- Part II: First-order ethics ----------
    { src: [0], term: "Utilitarianism",
      definition: "The first-order moral view composed of consequentialism plus the aim of maximizing happiness (utility); famous slogan: \"The greatest happiness of the greatest number.\"" },
    { src: [0], term: "Consequentialism",
      definition: "The view that an act should be assessed purely by its consequences." },
    { src: [0], term: "Moral absolutism", alt: ["Absolutism"],
      definition: "The view that certain kinds of acts are right or wrong whatever the consequences; the opposite of consequentialism, and also often called deontology." },
    { src: [0], term: "Deontology",
      definition: "Another name for moral absolutism: certain kinds of acts are right or wrong whatever the consequences." },
    { src: [0], kind: "person", term: "Jeremy Bentham", alt: ["Bentham"],
      definition: "Nineteenth-century British philosopher (1748-1832), one of the first utilitarians, who held that the consequences to consider are simply the happiness or unhappiness an action causes." },
    { src: [0], kind: "person", term: "James Mill", alt: ["Mill"],
      definition: "British philosopher (1773-1836) named alongside Bentham as one of the first utilitarians." },
    { src: [0], term: "Utility",
      definition: "The measure of happiness the utilitarians proposed so that totals could be added up across affected people; economists later defined it as a measure of the satisfaction of your desires." },
    { src: [0], term: "Interpersonal comparison of utility", alt: ["Interpersonal comparison", "Interpersonal comparisons of utility"],
      definition: "The problem of measuring desires precisely enough to weigh one person's happiness against another's; unless this is possible, utilitarianism cannot be applied." },
    { src: [0], term: "Epistemic challenge for consequentialists", alt: ["Epistemic challenge", "The epistemic challenge"],
      definition: "The difficulty that it is usually very hard to figure out what the overall consequences of an act will be, especially if long-term consequences matter." },
    { src: [0], kind: "person", term: "Jonathan Glover", alt: ["Glover"],
      definition: "British philosopher (1941-) whose case of offering to kill an unhappy prisoner who wants to go on living is an objection to utilitarianism and most forms of consequentialism." },
    { src: [0], term: "Autonomy",
      definition: "The capacity for self-rule (from the Greek \"nomos,\" law); respecting it means giving great weight to what people themselves judge to be important." },
    { src: [0], term: "Ends in themselves", alt: ["Ends in themselves, never merely means", "Never merely as means", "Treat people as ends"],
      definition: "Kant's idea, following from his universalizability principle, that we should never treat people merely as means but always as this." },
    { src: [0], term: "Rights", alt: ["Right"],
      definition: "What people have, beyond the capacity for happiness and pain, that should be respected; they can come into conflict, so a theory of them must adjudicate between competing claims and duties." },
    { src: [0], term: "Other-regarding", alt: ["Other regarding", "Other-regarding considerations"],
      definition: "Reasons for action that have to do with what sorts of treatment we owe to other people (e.g. the prohibition on killing the innocent, or questions about rights)." },
    { src: [0], term: "Self-regarding", alt: ["Self regarding", "Self-regarding considerations"],
      definition: "Considerations that have to do with what we owe to ourselves, in contexts where we owe nothing to anyone else (e.g. not procrastinating, not being imprudent)." },
    { src: [0], kind: "person", term: "Aristotle",
      definition: "Greek philosopher (384-322 BCE), in many ways the first great Western moral philosopher; wrote the Nicomachean Ethics and the Eudemian Ethics." },
    { src: [0], kind: "person", term: "Nicomachean Ethics", alt: ["The Nicomachean Ethics"],
      definition: "Aristotle's book whose aim is to say what it is to live one's life well; it deals with both self-regarding and other-regarding considerations." },
    { src: [0], term: "Eudaimonia", alt: ["Eudaemonia"],
      definition: "Aristotle's word for the state of someone who is living well; \"flourishing,\" often misleadingly translated as \"happiness.\"" },
    { src: [0], term: "Arete", alt: ["Arête"],
      definition: "Greek word usually translated \"virtue\" but probably better rendered as \"excellence.\"" },
    { src: [0], term: "Ethics", alt: ["Ethics (Aristotle's sense)"],
      definition: "In Aristotle's broad sense, the study of what it is to live a successful life: what it means for a life to be well lived (contrast the narrower question of what we owe to others)." },
    { src: [0], term: "Morality",
      definition: "In the narrow sense, the constraints that govern how we should and should not treat other people (contrast the broader question of what it is to live well)." },
    { src: [0], term: "Virtue ethics",
      definition: "The approach, revived from Aristotle, centered on the virtuous person: the right act is what such a person would do in the circumstances, for the reasons they would do it; character is primary." },
    { src: [0], term: "Virtue", alt: ["Virtues"],
      definition: "A character trait a person needs in order to have eudaimonia; a deep, stable, multi-track disposition that is intrinsically worth having." },
    { src: [0], term: "Vice", alt: ["Vices"],
      definition: "The antithesis of a virtue: a multi-track disposition (e.g. laziness, cruelty, arrogance) to be shunned, whose presence makes a life less worthwhile." },
    { src: [0], term: "Multi-track disposition", alt: ["Multi-track", "Multitrack disposition"],
      definition: "Hursthouse's description of a trait like honesty: concerned not just with honest actions but with emotions, choices, values, desires, perceptions, attitudes, and expectations." },
    { src: [0], kind: "person", term: "Rosalind Hursthouse", alt: ["Hursthouse"],
      definition: "New Zealand-based philosopher (1943-) whose three claims (right act = what a virtuous agent would do; virtuous person = one who has and exercises the virtues; virtue = trait needed to live well) form the core of virtue ethics." },
    // ---------- The diversity of ethical language ----------
    { src: [0], term: "Thin evaluative terms", alt: ["Thin", "Thin terms", "Thin concepts"],
      definition: "Terms like \"good\" and \"bad\" that express approval or disapproval but whose application is otherwise rather unconstrained (good soil, good argument, good man)." },
    { src: [0], term: "Thick evaluative terms", alt: ["Thick", "Thick terms", "Thick concepts"],
      definition: "Evaluative language (e.g. \"cruel,\" \"courageous,\" or ideas about family) that is enmeshed in particular ways of life, local customs, and factual beliefs." },
    { src: [0], term: "Abusua",
      definition: "The Akan group of people related by common ancestry through women, with relations of love and obligation; membership depends only on who your mother is." },
    { src: [0], term: "Matrilineal",
      definition: "Anthropologists' term for a conception of family, like the Akan one, in which membership passes only through women (\"like mitochondrial DNA\")." },
    { src: [0], term: "Wofa",
      definition: "In Akan society, your senior maternal uncle (mother's brother), who traditionally took on the responsibilities for a child that a father would have in England." },
    { src: [0], term: "Akyiwadee",
      definition: "Akan word meaning roughly \"a thing you turn your back on\"; translated in Ghanaian English as \"taboo\" (e.g. a clan's ban on eating a particular animal)." },
    { src: [0], term: "Taboo", alt: ["Taboos"],
      definition: "A word from a Polynesian language for things people of certain groups strenuously avoid; such values apply only to some people, pollute even when broken accidentally, and concern ritual pollution of oneself rather than how you treat others." },
    { src: [0], term: "Essentially contestable", alt: ["Essentially contested", "Essentially contested concepts", "Essential contestability"],
      definition: "Gallie's description of concepts whose \"proper use inevitably involves endless disputes about their proper use on the part of users\"; applying value terms to new cases requires judgment and discretion." },
    { src: [0], kind: "person", term: "W. B. Gallie", alt: ["Gallie", "WB Gallie"],
      definition: "Philosopher who introduced the term \"essentially contested concepts\" in a 1956 paper." },
    { src: [0], term: "Weighing values", alt: ["Weighing of values", "Relative weight of values"],
      definition: "A fourth source of disagreement: even people who share a value language and apply it the same way can disagree about how much importance to give different values (e.g. Confucius on obedience to authority)." },
    { src: [0], kind: "person", term: "Confucius",
      definition: "Author of the Analects, who says a son should respect his parents and who placed far more weight on obedience to authority than most of us would." },
    { src: [0], kind: "person", term: "Georg Wilhelm Friedrich Hegel", alt: ["Hegel", "G. W. F. Hegel", "GWF Hegel"],
      definition: "German philosopher (1770-1831) who famously said that tragedy involves the clash not between good and evil but between two goods." },
    { src: [0], term: "Practical agreement",
      definition: "Agreeing about what to do even when we do not agree why we should do it (e.g. agreeing with the Akan that incest is wrong without accepting their explanation)." },
    // ---------- Cross-cultural conversation (Appiah) ----------
    { src: [1], term: "Cross-cultural conversation", alt: ["Cross cultural conversation", "Conversation across cultures"],
      definition: "Talk between people of different societies whose value is not reaching agreement but getting used to one another, so that they can disagree without being disagreeable; modelled on ordinary talk among friends, not on a sermon." },
    { src: [1], term: "Cultural relativism", alt: ["Cultural relativism about morality"],
      definition: "The claim that moral beliefs can only be evaluated from within a shared cultural framework, so moral disagreements across cultures cannot be rationally resolved and conversation about them is pointless." },
    { src: [1], term: "True-for", alt: ["True for", "True-for-me", "True for me", "Relative truth"],
      definition: "The relativist's fallback that a moral claim can hold for one person and not another; it fails for moral judgments, since judging an act wrong commits you to wanting everyone to avoid it and believe it wrong." },
    { src: [1], term: "Moral anti-realism", alt: ["Anti-realism", "Antirealism", "Moral antirealism"],
      definition: "The view that no independent moral reality constrains our moral beliefs, so we cannot appeal to features of the world to persuade one another about morality." },
    { src: [1], term: "Open-textured", alt: ["Open textured", "Open texture"],
      definition: "Said of evaluative language where two people who both know what a word means can still reasonably disagree about whether it applies to a particular case; knowing the meaning gives no rule that settles every case." },
    { src: [1], term: "Disgust",
      definition: "An evolved response, tied to nausea, that helped an omnivorous species sort what to eat from what to avoid; culture can extend it to people and acts, which may underlie taboo reactions." },
    { src: [1], term: "Junzi", alt: ["Jūnzi", "君子", "Confucian gentleman"],
      definition: "Confucius's ideal person, often translated \"gentleman\": generous to those who have done well by him, free of vindictiveness and avarice, courageous, wise, and true to his word." },
    { src: [1], term: "Incompletely theorized agreements", alt: ["Incompletely theorized agreement"],
      definition: "Sunstein's term for agreeing on a practice or outcome, such as that banning mosques would be wrong, without agreeing on the theory or values that justify it." },
    { src: [1], term: "Modus vivendi",
      definition: "A way of living together that works without the parties agreeing on a shared set of fundamental values, as Jews and Christians did under Muslim rule in medieval Spain." },
    { src: [1], term: "Paul Rozin", kind: "person", alt: ["Rozin"],
      definition: "Psychologist whose cockroach-in-orange-juice experiments showed that disgust is a deep human trait not explained by the reasons people give for it." },
    { src: [1], term: "H. L. A. Hart", kind: "person", alt: ["Hart", "HLA Hart", "Herbert Hart"],
      definition: "Legal philosopher, author of The Concept of Law, who applied the idea of open-textured language to legal and evaluative terms." },
    { src: [1], term: "Cass Sunstein", kind: "person", alt: ["Sunstein"],
      definition: "Legal theorist who described American constitutional law as a set of incompletely theorized agreements." },
    { src: [1], term: "Charles Black", kind: "person", alt: ["Charles L. Black", "Black"],
      definition: "Legal scholar who argued that caprice and mistake are inevitable in capital trials, so the risk of killing an innocent person is too great to accept." },
    { src: [1], term: "Cosmopolitanism: Ethics in a World of Strangers", kind: "person", alt: ["Cosmopolitanism"],
      definition: "Appiah's 2006 book from which the cross-cultural conversation lecture draws its central arguments." }
  ]
});
