// Week 1: An Introduction to Ethics (based on Kwame Anthony Appiah,
// "Thinking It Through" ch. 5 and "Experiments in Ethics" ch. 2).
//
// Each card: { term, definition, alt? }
//   term       – what you must type
//   definition – what is shown as the prompt
//   alt        – other typed answers accepted as correct (optional)
window.VOCAB_SETS = window.VOCAB_SETS || [];
window.VOCAB_SETS.push({
  id: "ethics-week1",
  title: "Week 1: An Introduction to Ethics",
  source: "Week_1_An_Introduction_to_Ethics.pdf",
  cards: [
    // ---------- Part I: Meta-ethics ----------
    { term: "Principle K", alt: ["K"],
      definition: "\"Killing innocent people is wrong\": the example principle the essay opens with to show the two major kinds of issue in ethics (analysing a concept like innocence, and deciding whether a moral belief is true)." },
    { term: "Euthanasia",
      definition: "Killing a seriously ill person in great pain who asks to be killed; from a Greek expression meaning \"a good death.\"" },
    { term: "First-order moral questions", alt: ["First-order questions", "First order moral questions", "First-order"],
      definition: "Questions about what is right and wrong, good and bad; questions about which moral beliefs we should accept." },
    { term: "Meta-ethics", alt: ["Metaethics", "Meta-ethical questions"],
      definition: "Second-order questions about the nature, structure, and status of our first-order moral views." },
    { term: "Empiricism",
      definition: "The view that questions are to be settled by observation and experiment; does not seem a plausible view about morality." },
    { term: "A priori",
      definition: "Truths that can be known by reason alone, prior to (before) any particular experience; e.g. \"Green things are colored.\"" },
    { term: "A posteriori",
      definition: "Truths that require more than reason to discover; they can only be known after experience." },
    { term: "Epistemology",
      definition: "The study of the nature of knowledge and the justification of belief." },
    { term: "Moral rationalism",
      definition: "The view that moral questions are to be discovered by reason." },
    { term: "Factual questions", alt: ["Factual question", "Matters of fact"],
      definition: "Questions that observation, experiment, or proof alone can help us settle; there is a matter of fact about whether they are true, and logic and experience are ways of finding out." },
    { term: "Evaluative claim", alt: ["Evaluative claims", "Evaluative question", "Matters of value", "Matter of value"],
      definition: "A claim about value rather than fact; accepting one commits you to certain courses of action (you cannot reasonably accept that an act is wrong and then go ahead and do it)." },
    { term: "All things considered ought", alt: ["All things considered", "\"All things considered\" ought"],
      definition: "The kind of \"ought\" you assert once every relevant reason for and against acting has been weighed; it commits you to a course of action and is central to moral thinking." },
    { term: "David Hume", alt: ["Hume"],
      definition: "Eighteenth-century Scottish philosopher (1711-1776) who was one of the first to frame the difference between factual and evaluative questions as the difference between what is so and what ought to be so." },
    { term: "Fact-value distinction", alt: ["Fact/value distinction", "Is-ought distinction", "Is/ought distinction", "Is-ought gap"],
      definition: "The split between what is so and what ought to be so, central to all meta-ethics since Hume; summarized in the slogan \"you can't derive an 'ought' from an 'is.'\"" },
    { term: "Moral content question", alt: ["The moral content question"],
      definition: "The first of the two great questions of meta-ethics: \"What do moral judgments mean?\"" },
    { term: "Moral epistemology",
      definition: "The part of meta-ethics that answers the second great question, \"What justifies moral judgments?\"; it must show how moral beliefs are justified differently from factual ones." },
    { term: "Moral realism", alt: ["Realism"],
      definition: "The view that, just as ordinary facts \"out there\" determine whether factual claims are true, there are moral facts that determine the truth-values of moral claims." },
    { term: "Action-guiding", alt: ["Action guiding"],
      definition: "The essay's term for beliefs that commit us to action whatever our preferences or desires (as moral beliefs do), unlike factual beliefs, which guide action only in combination with a desire." },
    { term: "Categorical imperative", alt: ["Categorical imperatives"],
      definition: "Kant's name for an \"ought\" that a speaker would still assert whatever you said your wants and desires were." },
    { term: "Hypothetical imperative", alt: ["Hypothetical imperatives"],
      definition: "An \"ought\" that depends on a hypothesis about what you want, e.g. \"If you want to get there quickly, you ought to take a taxi.\"" },
    { term: "Immanuel Kant", alt: ["Kant"],
      definition: "German philosopher of the Enlightenment (1724-1804) who distinguished categorical from hypothetical imperatives and proposed the universalizability principle." },
    { term: "Elizabeth Anscombe", alt: ["Anscombe", "G. E. M. Anscombe"],
      definition: "British philosopher (1919-2001) who said \"The primitive sign of wanting is trying to get,\" cited to show that desires, unlike factual beliefs, lead directly to action." },
    { term: "Emotivism",
      definition: "The view that moral sentences express not beliefs but feelings, preferences, or desires (action-guiding states of mind)." },
    { term: "Pro-attitudes", alt: ["Pro-attitude", "Pro attitudes", "Pro attitude"],
      definition: "Action-guiding mental states that dispose you towards doing something." },
    { term: "Con-attitudes", alt: ["Con-attitude", "Con attitudes", "Con attitude"],
      definition: "Action-guiding mental states that dispose you against some action." },
    { term: "Attitudes", alt: ["Attitude"],
      definition: "The essay's collective term for the states that dispose you for or against an action (the \"pro\" and \"con\" kinds taken together)." },
    { term: "Cognitivism",
      definition: "The view in moral epistemology that we can have moral knowledge; tends to go with moral realism." },
    { term: "Non-cognitivism", alt: ["Noncognitivism", "Non cognitivism"],
      definition: "The view in moral epistemology that we cannot have moral knowledge, because moral sentences express attitudes, which cannot be true or false; tends to go with emotivism." },
    { term: "Intuitionism",
      definition: "G. E. Moore's form of cognitivism: we have a faculty that allows us to perceive moral qualities, just as the faculty of vision allows us to see colors." },
    { term: "Moral intuition",
      definition: "The faculty that, according to the intuitionist, lets us perceive goodness directly, the way vision lets us perceive yellowness." },
    { term: "G. E. Moore", alt: ["Moore", "GE Moore", "G.E. Moore", "George Edward Moore"],
      definition: "English philosopher (1873-1958), author of Principia Ethica, who combined moral realism with intuitionism and took goodness (not rightness or duty) as the basic moral concept." },
    { term: "Principia Ethica",
      definition: "Moore's book in which an action is one's duty \"if it will cause more good to exist in the universe than any other possible kind of alternative.\"" },
    { term: "Non-natural property", alt: ["Non-natural", "Nonnatural property"],
      definition: "Moore's description of goodness: a property that, unlike yellowness, cannot be studied by natural scientists or defined in terms of any other notions." },
    { term: "Natural property", alt: ["Natural properties"],
      definition: "Moore's term for properties like yellowness: the sorts of properties that could be studied by natural scientists." },
    { term: "Naturalistic fallacy",
      definition: "Moore's name for any attempt to identify a natural property with a non-natural one; now often used for any attempt to derive an \"ought\" from an \"is.\"" },
    { term: "Hedonism", alt: ["Hedonists", "Hedonist"],
      definition: "The view that once we know something gives people pleasure we can infer that it is good; the first utilitarians held it, since they sought to maximize happiness." },
    { term: "Alasdair MacIntyre", alt: ["MacIntyre"],
      definition: "British philosopher (1929-) who objected that Moore's view leaves it unexplained why something's being good should ever give us a reason for action; the analogy with yellow is a difficulty for it." },
    { term: "Moral relativism", alt: ["Relativism"],
      definition: "The view that what is good depends on who you are (or in what culture or when you live)." },
    { term: "Basic desire", alt: ["Basic desires"],
      definition: "A desire that is not dependent on a belief about means to some end; something we want \"for its own sake\" (e.g. giving a godchild an enjoyable afternoon)." },
    { term: "Universalizability principle", alt: ["Universalizability", "Kant's universalizability principle", "Principle of universalizability"],
      definition: "Kant's single categorical imperative: you ought to act only on maxims that you can at the same time will should become universal laws of nature." },
    { term: "Maxim", alt: ["Maxims"],
      definition: "Your general reason for acting in a particular way; the principle you must identify and then imagine becoming a law of nature when applying Kant's test." },
    { term: "Groundwork of the Metaphysic of Morals", alt: ["Groundwork", "Groundwork of the Metaphysics of Morals"],
      definition: "Kant's work arguing that the universalizability principle is the only categorical imperative, from which all the principles of morality derive." },
    { term: "Conan",
      definition: "The essay's imagined strong, well-armed psychopath who enjoys killing and is willing to universalize \"you may kill innocent people for fun\" (\"just let them try\"); Hare would call him a fanatic." },
    { term: "Adolf",
      definition: "The essay's imagined Nazi who gets around Kant's test by gerrymandering his maxim: \"You may kill innocent people if it suits you, provided they are not Aryans.\"" },
    { term: "Golden Rule", alt: ["The Golden Rule"],
      definition: "\"Do unto others as you would have them do unto you\": you shouldn't treat anybody in a way you would not like to be treated, whatever their race, gender, or age." },
    { term: "R. M. Hare", alt: ["Hare", "RM Hare", "R.M. Hare", "Richard Hare"],
      definition: "British philosopher (1919-2002), a prescriptivist and utilitarian, who added to Kant's formal demands the conditions that we treat everybody equally and consider consequences for sentient beings." },
    { term: "Sentient beings", alt: ["Sentient being"],
      definition: "Creatures capable, like us, of having experiences; Hare says we should consider the effects of possible actions on them." },
    { term: "Fanatic", alt: ["Fanatics"],
      definition: "Hare's name for someone willing to universalize maxims that allow them to do things to other people that they would not like done to themselves; there is something wrong with their imagination." },
    { term: "Prescriptivism",
      definition: "Hare's account of moral content: the meaning of moral terms is never equivalent to descriptive terms; moral sentences prescribe rather than describe, expressing attitudes and not just beliefs." },
    { term: "Supervenience", alt: ["Supervenient", "Supervene"],
      definition: "The relation whereby two actions or situations identical in their non-moral features must, as a matter of necessity, share their moral ones (compare: chemical properties on physical ones)." },
    // ---------- Part II: First-order ethics ----------
    { term: "Utilitarianism",
      definition: "The first-order moral view composed of consequentialism plus the aim of maximizing happiness (utility); famous slogan: \"The greatest happiness of the greatest number.\"" },
    { term: "Consequentialism",
      definition: "The view that an act should be assessed purely by its consequences." },
    { term: "Moral absolutism", alt: ["Absolutism"],
      definition: "The view that certain kinds of acts are right or wrong whatever the consequences; the opposite of consequentialism, and also often called deontology." },
    { term: "Deontology",
      definition: "Another name for moral absolutism: certain kinds of acts are right or wrong whatever the consequences." },
    { term: "Jeremy Bentham", alt: ["Bentham"],
      definition: "Nineteenth-century British philosopher (1748-1832), one of the first utilitarians, who held that the consequences to consider are simply the happiness or unhappiness an action causes." },
    { term: "James Mill", alt: ["Mill"],
      definition: "British philosopher (1773-1836) named alongside Bentham as one of the first utilitarians." },
    { term: "Utility",
      definition: "The measure of happiness the utilitarians proposed so that totals could be added up across affected people; economists later defined it as a measure of the satisfaction of your desires." },
    { term: "Interpersonal comparison of utility", alt: ["Interpersonal comparison", "Interpersonal comparisons of utility"],
      definition: "The problem of measuring desires precisely enough to weigh one person's happiness against another's; unless this is possible, utilitarianism cannot be applied." },
    { term: "Theresa",
      definition: "The essay's example of an absolutist about lying who nonetheless lies to a police officer to protect a hidden dissident, judging it the lesser of two evils and regretting having to lie." },
    { term: "Lesser of two evils", alt: ["The lesser of two evils", "Lesser evil"],
      definition: "An absolutist's description of an act that is still wrong (e.g. a lie) but is chosen because the alternative (e.g. betraying a noble individual) is worse." },
    { term: "Epistemic challenge for consequentialists", alt: ["Epistemic challenge", "The epistemic challenge"],
      definition: "The difficulty that it is usually very hard to figure out what the overall consequences of an act will be, especially if long-term consequences matter." },
    { term: "Jonathan Glover", alt: ["Glover"],
      definition: "British philosopher (1941-) whose case of offering to kill an unhappy prisoner who wants to go on living is an objection to utilitarianism and most forms of consequentialism." },
    { term: "Autonomy",
      definition: "The capacity for self-rule (from the Greek \"nomos,\" law); respecting it means giving great weight to what people themselves judge to be important." },
    { term: "Ends in themselves", alt: ["Ends in themselves, never merely means", "Never merely as means", "Treat people as ends"],
      definition: "Kant's idea, following from his universalizability principle, that we should never treat people merely as means but always as this." },
    { term: "Rights", alt: ["Right"],
      definition: "What people have, beyond the capacity for happiness and pain, that should be respected; they can come into conflict, so a theory of them must adjudicate between competing claims and duties." },
    { term: "Other-regarding", alt: ["Other regarding", "Other-regarding considerations"],
      definition: "Reasons for action that have to do with what sorts of treatment we owe to other people (e.g. the prohibition on killing the innocent, or questions about rights)." },
    { term: "Self-regarding", alt: ["Self regarding", "Self-regarding considerations"],
      definition: "Considerations that have to do with what we owe to ourselves, in contexts where we owe nothing to anyone else (e.g. not procrastinating, not being imprudent)." },
    { term: "Procrastination",
      definition: "Doing things at the last minute, when they are harder to do than they would have been if done earlier; Johnny's self-regarding failing." },
    { term: "Imprudence", alt: ["Imprudent"],
      definition: "Taking absurd risks with one's own life while harming no one else, from not preparing for exams to stepping into the street without looking; Mary's self-regarding failing." },
    { term: "Aristotle",
      definition: "Greek philosopher (384-322 BCE), in many ways the first great Western moral philosopher; wrote the Nicomachean Ethics and the Eudemian Ethics." },
    { term: "Nicomachean Ethics", alt: ["The Nicomachean Ethics"],
      definition: "Aristotle's book whose aim is to say what it is to live one's life well; it deals with both self-regarding and other-regarding considerations." },
    { term: "Eudaimonia", alt: ["Eudaemonia", "Flourishing"],
      definition: "Aristotle's word for the state of someone who is living well; \"flourishing,\" often misleadingly translated as \"happiness.\"" },
    { term: "Arete", alt: ["Arête"],
      definition: "Greek word usually translated \"virtue\" but probably better rendered as \"excellence.\"" },
    { term: "Ethics", alt: ["Ethics (Aristotle's sense)"],
      definition: "In Aristotle's and the essay's usage, the study of what it is to live a successful life: what it means for a life to be well lived." },
    { term: "Morality",
      definition: "In the essay's narrower usage, the constraints that govern how we should and should not treat other people." },
    { term: "Virtue ethics",
      definition: "The approach, revived from Aristotle, centered on the virtuous person: the right act is what such a person would do in the circumstances, for the reasons they would do it; character is primary." },
    { term: "Virtue", alt: ["Virtues"],
      definition: "A character trait a person needs in order to have eudaimonia; a deep, stable, multi-track disposition that is intrinsically worth having." },
    { term: "Vice", alt: ["Vices"],
      definition: "The antithesis of a virtue: a multi-track disposition (e.g. laziness, cruelty, arrogance) to be shunned, whose presence makes a life less worthwhile." },
    { term: "Multi-track disposition", alt: ["Multi-track", "Multitrack disposition"],
      definition: "Hursthouse's description of a trait like honesty: concerned not just with honest actions but with emotions, choices, values, desires, perceptions, attitudes, and expectations." },
    { term: "Rosalind Hursthouse", alt: ["Hursthouse"],
      definition: "New Zealand-based philosopher (1943-) whose three claims (right act = what a virtuous agent would do; virtuous person = one who has and exercises the virtues; virtue = trait needed to live well) form the core of virtue ethics." },
    // ---------- The diversity of ethical language ----------
    { term: "Thin evaluative terms", alt: ["Thin", "Thin terms", "Thin concepts"],
      definition: "Terms like \"good\" and \"bad\" that express approval or disapproval but whose application is otherwise rather unconstrained (good soil, good argument, good man)." },
    { term: "Thick evaluative terms", alt: ["Thick", "Thick terms", "Thick concepts"],
      definition: "Evaluative language (e.g. \"cruel,\" \"courageous,\" or ideas about family) that is enmeshed in particular ways of life, local customs, and factual beliefs." },
    { term: "Abusua",
      definition: "The Akan group of people related by common ancestry through women, with relations of love and obligation; membership depends only on who your mother is." },
    { term: "Matrilineal",
      definition: "Anthropologists' term for a conception of family, like the Akan one, in which membership passes only through women (\"like mitochondrial DNA\")." },
    { term: "Wofa",
      definition: "In Akan society, your senior maternal uncle (mother's brother), who a century ago in Asante played the role a father would have been expected to play in England." },
    { term: "Akyiwadee",
      definition: "Akan word meaning roughly \"a thing you turn your back on\"; translated in Ghanaian English as \"taboo\" (e.g. bush meat for the Bush Cow clan)." },
    { term: "Taboo", alt: ["Taboos"],
      definition: "A word from a Polynesian language for things people of certain groups strenuously avoid; such values apply only to some people, pollute even when broken accidentally, and concern ritual pollution of oneself rather than how you treat others." },
    { term: "Holiness Code", alt: ["The Holiness Code"],
      definition: "The chapters at the end of Leviticus containing rules on washing, blood, self-mutilation, and sexual acts that many people now regard as taboos." },
    { term: "Essentially contestable", alt: ["Essentially contested", "Essentially contested concepts", "Essential contestability"],
      definition: "Gallie's description of concepts whose \"proper use inevitably involves endless disputes about their proper use on the part of users\"; applying value terms to new cases requires judgment and discretion." },
    { term: "W. B. Gallie", alt: ["Gallie", "WB Gallie"],
      definition: "Philosopher who introduced the term \"essentially contested concepts\" in a 1956 paper." },
    { term: "Weighing values", alt: ["Weighing of values", "Relative weight of values"],
      definition: "A fourth source of disagreement: even people who share a value language and apply it the same way can disagree about how much importance to give different values (e.g. Confucius on obedience to authority)." },
    { term: "Confucius",
      definition: "Author of the Analects, who says a son should respect his parents and who placed far more weight on obedience to authority than most of us would." },
    { term: "Georg Wilhelm Friedrich Hegel", alt: ["Hegel", "G. W. F. Hegel", "GWF Hegel"],
      definition: "German philosopher (1770-1831) who famously said that tragedy involves the clash not between good and evil but between two goods." },
    { term: "Agamemnon",
      definition: "Commander of the Greek army who had to choose between the interests of the Trojan expedition and his devotion to his wife and daughter; an example of a clash between two goods." },
    { term: "Sophie's Choice", alt: ["Sophies Choice"],
      definition: "Novel and film in which a mother at Auschwitz is forced to choose which of her two children to save: a clash between treating your children equally and protecting them." },
    { term: "Sources of disagreement about values", alt: ["Sources of disagreement", "Three sources of disagreement"],
      definition: "(a) failing to share a vocabulary of evaluation; (b) giving the same vocabulary different interpretations; (c) giving the same values different weights." },
    { term: "Practical agreement",
      definition: "Agreeing about what to do even when we do not agree why we should do it (e.g. agreeing with the Akan that incest is wrong without accepting their explanation)." },
    { term: "Reasoning", alt: ["Reasoning (public sense)"],
      definition: "In the essay's closing sense, the public act of exchanging stated justifications; it becomes salient not when we go on in the usual way but when we are thinking about change." },
    { term: "Cross-cultural conversation", alt: ["Cross cultural conversation"],
      definition: "Worthwhile not because it is likely to produce reasoned agreement about values, but because it helps us get used to one another." },
    { term: "Kwame Anthony Appiah", alt: ["Appiah", "Anthony Appiah"],
      definition: "Author of Thinking It Through and Experiments in Ethics, the books on which the Week 1 essay is based; grew up in Akan society in Ghana and in his mother's English world." }
  ]
});
