// Operations Management, week 1: Process analysis (OPMG-UB 1, Session 2 pre-class slides).
window.VOCAB_SETS = window.VOCAB_SETS || [];
window.VOCAB_SETS.push({
  id: "opsmgmt-week1",
  course: "Operations Management",
  week: 1,
  title: "Process Analysis",
  materials: ["Operations_Management_Preclass_Slides.pdf"],
  cards: [
    { src: [0], term: "Flow unit", alt: ["Flow units"],
      definition: "The item that moves through a process and is counted at each step: an order, a customer, a part, a patient." },
    { src: [0], term: "Resource", alt: ["Resources"],
      definition: "A person, machine, or station that performs work on flow units; each one has its own capacity, and bottlenecks are always one of these, never an activity or step." },
    { src: [0], term: "Arrival rate", alt: ["Input rate"],
      definition: "The number of flow units entering a process per unit of time, e.g. 15 customers per hour." },
    { src: [0], term: "Inventory",
      definition: "The number of flow units currently inside a process, whether being worked on or waiting between steps." },
    { src: [0], term: "Work in process", alt: ["WIP", "Work-in-process", "Work in progress"],
      definition: "Flow units that have entered the process but not yet left it, typically waiting in a buffer between two steps." },
    { src: [0], term: "Flow time", alt: ["Throughput time"],
      definition: "The total time one flow unit takes to move through a process from entry to exit, including any waiting." },
    { src: [0], term: "Throughput rate", alt: ["Throughput", "Output rate"],
      definition: "The number of flow units leaving a process per unit of time; it equals the smaller of the input rate and the process capacity." },
    { src: [0], term: "Cycle time",
      definition: "The time between two consecutive flow units leaving a process; equal to 1 divided by the throughput rate, and not the same as flow time." },
    { src: [0], term: "Processing time", alt: ["Process time", "Activity time"],
      definition: "The time a single resource spends on one flow unit at its step, e.g. 4 minutes per burrito; a resource's capacity is 1 divided by this." },
    { src: [0], term: "Capacity",
      definition: "The maximum possible output rate of a resource, e.g. 15 orders per hour for one chef; adding a second identical resource doubles it." },
    { src: [0], term: "Process capacity",
      definition: "The maximum output rate of the whole process, set by the resource with the lowest capacity." },
    { src: [0], term: "Bottleneck", alt: ["Bottleneck resource"],
      definition: "The resource with the lowest capacity (longest processing time) in a process; it caps process capacity and must stay 100% busy for maximum throughput. Adding resources can move it elsewhere." },
    { src: [0], term: "Capacity-constrained process", alt: ["Capacity constrained", "Capacity-constrained"],
      definition: "A process where demand exceeds the bottleneck's capacity: throughput rate equals the bottleneck capacity and cycle time equals the bottleneck's processing time." },
    { src: [0], term: "Demand-constrained process", alt: ["Demand constrained", "Demand-constrained"],
      definition: "A process where demand is below the bottleneck's capacity: throughput rate equals the demand rate and cycle time equals the time between arrivals." },
    { src: [0], term: "Flow diagram", alt: ["Process flow diagram", "Flow chart"],
      definition: "A drawing of a process as boxes for steps or resources, arrows for the path flow units take, and triangles for the buffers between them." },
    { src: [0], term: "Gantt chart",
      definition: "A timeline with one row per resource showing when each flow unit occupies it, used to see step durations, dependencies, idle time, and which resource limits output." }
  ]
});
